// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/kubernetes/kubernetescnpgbarmancloudplugin/v1alpha1/spec.proto

package kubernetescnpgbarmancloudpluginv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	kubernetes "github.com/plantonhq/planton/catalog/kubernetes"
	v1 "github.com/plantonhq/planton/shared/foreignkey/v1"
	_ "github.com/plantonhq/planton/shared/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// **KubernetesCnpgBarmanCloudPluginSpec** installs the Barman Cloud plugin
// for CloudNativePG from the official Helm chart (`plugin-barman-cloud` at
// https://cloudnative-pg.github.io/charts). The plugin is the object-store
// backup path for every PostgreSQL cluster the operator manages: WAL
// archiving, scheduled base backups, and restores to S3, S3-compatible
// stores, GCS, and Azure Blob. CloudNativePG's built-in object-store
// support is deprecated upstream, so a KubernetesPostgres `backup` block
// (or an object-store `bootstrap.recovery`) renders its Cluster against
// THIS plugin and does nothing without it -- the operator parks such a
// Cluster in the phase "Cluster cannot proceed to reconciliation due to an
// unknown plugin being required" and never creates its instances.
//
// ONE PLUGIN PER CLUSTER, IN THE OPERATOR'S NAMESPACE. CloudNativePG
// discovers plugins through Services labeled `cnpg.io/pluginName` in its
// OWN namespace only (a plugin anywhere else is invisible to it), and the
// chart fixes that Service's name to `barman-cloud` because it is baked
// into the plugin's TLS certificate. So the plugin is a per-namespace
// singleton by construction, and the Helm release name is fixed to
// "plugin-barman-cloud" -- a second declaration in the same namespace
// would fight the first over those fixed-name objects.
//
// WHO INSTALLS IT. Beside a CloudNativePG declared with the catalog's
// KubernetesCloudNativePgOperator: this resource, with `namespace`
// referencing that operator resource. Beside a CloudNativePG someone else
// installed (Helm, GitOps, a platform operator that manages its own copy):
// this resource with the operator's namespace as a literal -- unless that
// installer also owns a plugin toggle, in which case enable it THERE; two
// owners of the singleton collide.
//
// REQUIRES cert-manager on the cluster (KubernetesCertManager): the chart
// renders a self-signed Issuer and two Certificates for the operator <->
// plugin gRPC TLS unconditionally, and the release fails to install without
// it. Requires a CloudNativePG at 1.26 or later (1.27 or later strongly
// recommended upstream for its plugin error reporting); the catalog
// operator's default chart ships 1.30.0.
//
// The typed fields below cover the chart's meaningful configuration
// surface; `helm_values` remains as the escape hatch for chart values
// beyond them (merged last, Helm `-f` semantics, identical on both
// engines) -- a safety valve, never the primary interface.
type KubernetesCnpgBarmanCloudPluginSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Namespace to install the plugin into. This MUST be the namespace the
	// CloudNativePG operator runs in: the operator only considers plugin
	// Services in its own namespace, so a plugin elsewhere is never
	// discovered and every backup-declaring database stays unreconciled.
	// Reference the operator resource (a bare `valueFrom` with the resource
	// name resolves to its namespace output), or pass the literal namespace
	// of a CloudNativePG someone else installed ("cnpg-system" is the
	// upstream convention).
	Namespace *v1.StringValueOrRef `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// *
	// When true, the namespace is created (with the standard Planton
	// governance labels) before installing and deleted with the resource.
	// Almost always false here: the namespace is the OPERATOR's and already
	// exists (created by the operator resource or by whoever installed the
	// resident CloudNativePG). True is only correct when this resource is
	// the first thing to claim the namespace -- and then deleting the plugin
	// deletes the operator's namespace with it.
	CreateNamespace bool `protobuf:"varint,2,opt,name=create_namespace,json=createNamespace,proto3" json:"create_namespace,omitempty"`
	// *
	// Helm chart version to install (e.g. "0.7.0", which ships plugin
	// v0.13.0 -- chart and app versions move separately; the chart pin
	// governs). Pin deliberately; upgrades re-run the release with the new
	// chart. Pick versions from the chart repository's index
	// (`helm search repo`): the served chart is the contract. Plugin
	// v0.13.0 requires CloudNativePG 1.26 or later and upstream strongly
	// recommends 1.27 or later (it reports plugin errors on the Cluster's
	// status instead of only in logs); check the plugin's release notes
	// when moving the pin against an older operator.
	ChartVersion *string `protobuf:"bytes,3,opt,name=chart_version,json=chartVersion,proto3,oneof" json:"chart_version,omitempty"`
	// *
	// The plugin's custom resource definition (`ObjectStore`, the object
	// store a KubernetesPostgres backup block points at) lifecycle.
	Crds *KubernetesCnpgBarmanCloudPluginCrds `protobuf:"bytes,4,opt,name=crds,proto3" json:"crds,omitempty"`
	// *
	// Plugin replica count. Chart default: 1. The chart deploys with the
	// Recreate strategy (the plugin does not support rolling updates yet),
	// and extra replicas are leader-elected standbys that shorten failover of
	// the PLUGIN itself -- they add no backup throughput.
	Replicas *int32 `protobuf:"varint,5,opt,name=replicas,proto3,oneof" json:"replicas,omitempty"`
	// *
	// Plugin container resources. Empty = no requests/limits (the chart
	// ships none by default). The plugin process itself is light; the
	// backup work runs in a sidecar the plugin injects into each PostgreSQL
	// instance pod, sized by the database's own resources.
	Resources *kubernetes.ContainerResources `protobuf:"bytes,6,opt,name=resources,proto3" json:"resources,omitempty"`
	// *
	// Override the plugin image (registry mirrors, air-gapped clusters).
	// Empty = the chart default (ghcr.io/cloudnative-pg/plugin-barman-cloud
	// at the chart's app version).
	Image *KubernetesCnpgBarmanCloudPluginImage `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	// *
	// Override the SIDECAR image -- the container the plugin injects into
	// every PostgreSQL instance pod to run the actual archiving and backup
	// commands. Empty = the chart default
	// (ghcr.io/cloudnative-pg/plugin-barman-cloud-sidecar at the chart's
	// app version). Mirror BOTH images for an air-gapped cluster: the
	// database pods pull this one, not the plugin's.
	SidecarImage *KubernetesCnpgBarmanCloudPluginImage `protobuf:"bytes,8,opt,name=sidecar_image,json=sidecarImage,proto3" json:"sidecar_image,omitempty"`
	// *
	// Names of image-pull secrets (in the installation namespace) for
	// pulling the plugin image from a private mirror. The sidecar image is
	// pulled by the DATABASE pods in their own namespaces -- give those
	// clusters their own pull secrets (KubernetesPostgres) when the sidecar
	// is mirrored too.
	ImagePullSecrets []string `protobuf:"bytes,9,rep,name=image_pull_secrets,json=imagePullSecrets,proto3" json:"image_pull_secrets,omitempty"`
	// *
	// PriorityClass for the plugin pod. Backups and WAL archiving stop
	// silently-for-a-while when the plugin is evicted (the databases keep
	// running, the archive falls behind) -- keep it at the operator's
	// priority.
	PriorityClassName string `protobuf:"bytes,10,opt,name=priority_class_name,json=priorityClassName,proto3" json:"priority_class_name,omitempty"`
	// *
	// Node selector for the plugin pod.
	NodeSelector map[string]string `protobuf:"bytes,11,rep,name=node_selector,json=nodeSelector,proto3" json:"node_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// *
	// Tolerations for the plugin pod.
	Tolerations []*kubernetes.WorkloadToleration `protobuf:"bytes,12,rep,name=tolerations,proto3" json:"tolerations,omitempty"`
	// *
	// Escape hatch: additional chart values as a YAML document, merged LAST
	// over everything the typed fields render (Helm `-f` semantics,
	// identical on both engines). For the chart surface beyond the typed
	// fields (additionalArgs, additionalEnv, update strategy, security
	// contexts, topology spread, host network, certificate durations, ...)
	// -- never the substitute for them. The chart's fixed identities
	// (`service.name`, the name overrides) are re-pinned after this merge:
	// the Service name is baked into the plugin's TLS certificate and the
	// release name is what a re-install adopts the kept CRD through, so
	// neither is configurable here. Do not put secrets here.
	HelmValues    string `protobuf:"bytes,13,opt,name=helm_values,json=helmValues,proto3" json:"helm_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesCnpgBarmanCloudPluginSpec) Reset() {
	*x = KubernetesCnpgBarmanCloudPluginSpec{}
	mi := &file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesCnpgBarmanCloudPluginSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesCnpgBarmanCloudPluginSpec) ProtoMessage() {}

func (x *KubernetesCnpgBarmanCloudPluginSpec) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesCnpgBarmanCloudPluginSpec.ProtoReflect.Descriptor instead.
func (*KubernetesCnpgBarmanCloudPluginSpec) Descriptor() ([]byte, []int) {
	return file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *KubernetesCnpgBarmanCloudPluginSpec) GetNamespace() *v1.StringValueOrRef {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *KubernetesCnpgBarmanCloudPluginSpec) GetCreateNamespace() bool {
	if x != nil {
		return x.CreateNamespace
	}
	return false
}

func (x *KubernetesCnpgBarmanCloudPluginSpec) GetChartVersion() string {
	if x != nil && x.ChartVersion != nil {
		return *x.ChartVersion
	}
	return ""
}

func (x *KubernetesCnpgBarmanCloudPluginSpec) GetCrds() *KubernetesCnpgBarmanCloudPluginCrds {
	if x != nil {
		return x.Crds
	}
	return nil
}

func (x *KubernetesCnpgBarmanCloudPluginSpec) GetReplicas() int32 {
	if x != nil && x.Replicas != nil {
		return *x.Replicas
	}
	return 0
}

func (x *KubernetesCnpgBarmanCloudPluginSpec) GetResources() *kubernetes.ContainerResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *KubernetesCnpgBarmanCloudPluginSpec) GetImage() *KubernetesCnpgBarmanCloudPluginImage {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *KubernetesCnpgBarmanCloudPluginSpec) GetSidecarImage() *KubernetesCnpgBarmanCloudPluginImage {
	if x != nil {
		return x.SidecarImage
	}
	return nil
}

func (x *KubernetesCnpgBarmanCloudPluginSpec) GetImagePullSecrets() []string {
	if x != nil {
		return x.ImagePullSecrets
	}
	return nil
}

func (x *KubernetesCnpgBarmanCloudPluginSpec) GetPriorityClassName() string {
	if x != nil {
		return x.PriorityClassName
	}
	return ""
}

func (x *KubernetesCnpgBarmanCloudPluginSpec) GetNodeSelector() map[string]string {
	if x != nil {
		return x.NodeSelector
	}
	return nil
}

func (x *KubernetesCnpgBarmanCloudPluginSpec) GetTolerations() []*kubernetes.WorkloadToleration {
	if x != nil {
		return x.Tolerations
	}
	return nil
}

func (x *KubernetesCnpgBarmanCloudPluginSpec) GetHelmValues() string {
	if x != nil {
		return x.HelmValues
	}
	return ""
}

// *
// Plugin CRD lifecycle.
type KubernetesCnpgBarmanCloudPluginCrds struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Install the `ObjectStore` CRD with the release. Chart default: true.
	// Disable only when something else manages it. The chart stamps the CRD
	// with `helm.sh/resource-policy: keep`, so uninstalling the release
	// NEVER deletes the ObjectStore resources databases point at (and the
	// backup configuration they carry) -- the upstream safety posture, kept
	// as-is. A later install with the SAME release name and namespace adopts
	// the kept CRD; that adoption is one more reason the release name is
	// fixed.
	Install       *bool `protobuf:"varint,1,opt,name=install,proto3,oneof" json:"install,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesCnpgBarmanCloudPluginCrds) Reset() {
	*x = KubernetesCnpgBarmanCloudPluginCrds{}
	mi := &file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesCnpgBarmanCloudPluginCrds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesCnpgBarmanCloudPluginCrds) ProtoMessage() {}

func (x *KubernetesCnpgBarmanCloudPluginCrds) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesCnpgBarmanCloudPluginCrds.ProtoReflect.Descriptor instead.
func (*KubernetesCnpgBarmanCloudPluginCrds) Descriptor() ([]byte, []int) {
	return file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_rawDescGZIP(), []int{1}
}

func (x *KubernetesCnpgBarmanCloudPluginCrds) GetInstall() bool {
	if x != nil && x.Install != nil {
		return *x.Install
	}
	return false
}

// *
// Container image override (the chart takes the image as a registry plus
// a repository; the modules split a combined reference on the container
// runtime rule -- the first path segment is the registry when it carries
// a dot, a colon, or is "localhost").
type KubernetesCnpgBarmanCloudPluginImage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Image repository including its registry (e.g.
	// "my-mirror.example.com/cloudnative-pg/plugin-barman-cloud").
	Repository string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// *
	// Image tag. Empty = the chart's app version.
	Tag           string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesCnpgBarmanCloudPluginImage) Reset() {
	*x = KubernetesCnpgBarmanCloudPluginImage{}
	mi := &file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesCnpgBarmanCloudPluginImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesCnpgBarmanCloudPluginImage) ProtoMessage() {}

func (x *KubernetesCnpgBarmanCloudPluginImage) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesCnpgBarmanCloudPluginImage.ProtoReflect.Descriptor instead.
func (*KubernetesCnpgBarmanCloudPluginImage) Descriptor() ([]byte, []int) {
	return file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_rawDescGZIP(), []int{2}
}

func (x *KubernetesCnpgBarmanCloudPluginImage) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *KubernetesCnpgBarmanCloudPluginImage) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

var File_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto protoreflect.FileDescriptor

const file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_rawDesc = "" +
	"\n" +
	"Fcatalog/kubernetes/kubernetescnpgbarmancloudplugin/v1alpha1/spec.proto\x12?dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a#catalog/kubernetes/kubernetes.proto\x1a%catalog/kubernetes/workload_pod.proto\x1a&shared/foreignkey/v1/foreign_key.proto\x1a\x1cshared/options/options.proto\"\x94\n" +
	"\n" +
	"#KubernetesCnpgBarmanCloudPluginSpec\x12y\n" +
	"\tnamespace\x18\x01 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB'\xbaH\x03\xc8\x01\x01\x88\xd4a\x84 \x92\xd4a\x18status.outputs.namespaceR\tnamespace\x12)\n" +
	"\x10create_namespace\x18\x02 \x01(\bR\x0fcreateNamespace\x123\n" +
	"\rchart_version\x18\x03 \x01(\tB\t\x8a\xa6\x1d\x050.7.0H\x00R\fchartVersion\x88\x01\x01\x12x\n" +
	"\x04crds\x18\x04 \x01(\v2d.dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginCrdsR\x04crds\x12-\n" +
	"\breplicas\x18\x05 \x01(\x05B\f\xbaH\x04\x1a\x02(\x01\x8a\xa6\x1d\x011H\x01R\breplicas\x88\x01\x01\x12H\n" +
	"\tresources\x18\x06 \x01(\v2*.dev.planton.kubernetes.ContainerResourcesR\tresources\x12{\n" +
	"\x05image\x18\a \x01(\v2e.dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginImageR\x05image\x12\x8a\x01\n" +
	"\rsidecar_image\x18\b \x01(\v2e.dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginImageR\fsidecarImage\x12x\n" +
	"\x12image_pull_secrets\x18\t \x03(\tBJ\xaa\xa6\x1dFNames of existing Kubernetes Secrets (references), not secret materialR\x10imagePullSecrets\x12.\n" +
	"\x13priority_class_name\x18\n" +
	" \x01(\tR\x11priorityClassName\x12\x9b\x01\n" +
	"\rnode_selector\x18\v \x03(\v2v.dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginSpec.NodeSelectorEntryR\fnodeSelector\x12L\n" +
	"\vtolerations\x18\f \x03(\v2*.dev.planton.kubernetes.WorkloadTolerationR\vtolerations\x12\x1f\n" +
	"\vhelm_values\x18\r \x01(\tR\n" +
	"helmValues\x1a?\n" +
	"\x11NodeSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x10\n" +
	"\x0e_chart_versionB\v\n" +
	"\t_replicas\"Z\n" +
	"#KubernetesCnpgBarmanCloudPluginCrds\x12'\n" +
	"\ainstall\x18\x01 \x01(\bB\b\x8a\xa6\x1d\x04trueH\x00R\ainstall\x88\x01\x01B\n" +
	"\n" +
	"\b_install\"X\n" +
	"$KubernetesCnpgBarmanCloudPluginImage\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tagB\xf4\x03\n" +
	"Ccom.dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1B\tSpecProtoP\x01Z\x80\x01github.com/plantonhq/planton/catalog/kubernetes/kubernetescnpgbarmancloudplugin/v1alpha1;kubernetescnpgbarmancloudpluginv1alpha1\xa2\x02\x04DPKK\xaa\x02?Dev.Planton.Kubernetes.Kubernetescnpgbarmancloudplugin.V1alpha1\xca\x02?Dev\\Planton\\Kubernetes\\Kubernetescnpgbarmancloudplugin\\V1alpha1\xe2\x02KDev\\Planton\\Kubernetes\\Kubernetescnpgbarmancloudplugin\\V1alpha1\\GPBMetadata\xea\x02CDev::Planton::Kubernetes::Kubernetescnpgbarmancloudplugin::V1alpha1b\x06proto3"

var (
	file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_rawDescOnce sync.Once
	file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_rawDescData []byte
)

func file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_rawDescGZIP() []byte {
	file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_rawDescOnce.Do(func() {
		file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_rawDesc), len(file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_rawDesc)))
	})
	return file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_rawDescData
}

var file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_goTypes = []any{
	(*KubernetesCnpgBarmanCloudPluginSpec)(nil),  // 0: dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginSpec
	(*KubernetesCnpgBarmanCloudPluginCrds)(nil),  // 1: dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginCrds
	(*KubernetesCnpgBarmanCloudPluginImage)(nil), // 2: dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginImage
	nil,                                   // 3: dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginSpec.NodeSelectorEntry
	(*v1.StringValueOrRef)(nil),           // 4: dev.planton.shared.foreignkey.v1.StringValueOrRef
	(*kubernetes.ContainerResources)(nil), // 5: dev.planton.kubernetes.ContainerResources
	(*kubernetes.WorkloadToleration)(nil), // 6: dev.planton.kubernetes.WorkloadToleration
}
var file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_depIdxs = []int32{
	4, // 0: dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginSpec.namespace:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	1, // 1: dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginSpec.crds:type_name -> dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginCrds
	5, // 2: dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginSpec.resources:type_name -> dev.planton.kubernetes.ContainerResources
	2, // 3: dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginSpec.image:type_name -> dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginImage
	2, // 4: dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginSpec.sidecar_image:type_name -> dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginImage
	3, // 5: dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginSpec.node_selector:type_name -> dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginSpec.NodeSelectorEntry
	6, // 6: dev.planton.kubernetes.kubernetescnpgbarmancloudplugin.v1alpha1.KubernetesCnpgBarmanCloudPluginSpec.tolerations:type_name -> dev.planton.kubernetes.WorkloadToleration
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_init() }
func file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_init() {
	if File_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto != nil {
		return
	}
	file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_msgTypes[0].OneofWrappers = []any{}
	file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_rawDesc), len(file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_goTypes,
		DependencyIndexes: file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_depIdxs,
		MessageInfos:      file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_msgTypes,
	}.Build()
	File_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto = out.File
	file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_goTypes = nil
	file_catalog_kubernetes_kubernetescnpgbarmancloudplugin_v1alpha1_spec_proto_depIdxs = nil
}
