<#ftl output_format="plainText">
<#-- Generated by @planton/email-templates from src/layout; edit the source and run yarn compile. -->
<#macro textLayout>
${properties.brandName}

<#nested>

--
Sent by ${properties.brandName}<#if properties.consoleHost?has_content> from ${properties.consoleHost} (${properties.consoleUrl})</#if>.
<#if properties.replyTo?has_content>Questions? Write to ${properties.replyTo}.</#if>
</#macro>
