package keycloaklogintheme

import (
	"bytes"
	"regexp"
	"strings"
	"testing"
)

// The ConfigMap the operator materializes this theme into has a hard 1MiB
// ceiling; leave real headroom so adding an artifact never becomes a
// production surprise.
const configMapSizeBudget = 512 * 1024

var acme = EmailFacts{BrandName: "Acme Platform", ConsoleURL: "https://planton.acme.com", ReplyTo: "it-help@acme.com"}

func TestFilesCarriesEveryArtifact(t *testing.T) {
	files := Files(acme)

	for _, p := range []string{
		PathThemeProperties, PathStylesCSS, PathLogoSVG, PathInterFontWOFF2,
		PathEmailThemeProperties, PathEmailHTMLLayout, PathEmailTextLayout, PathEmailMessages,
		"email/html/password-reset.ftl", "email/text/password-reset.ftl",
		"email/html/executeActions.ftl", "email/text/executeActions.ftl",
		"email/html/email-verification.ftl", "email/text/email-verification.ftl",
		"email/html/email-test.ftl", "email/text/email-test.ftl",
	} {
		content, ok := files[p]
		if !ok {
			t.Fatalf("Files() is missing %q", p)
		}
		if len(content) == 0 {
			t.Fatalf("Files()[%q] is empty", p)
		}
	}
	for p := range files {
		if strings.HasPrefix(p, "theme/") || strings.HasPrefix(p, "/") {
			t.Errorf("path %q is not relative to the theme root", p)
		}
		if !strings.HasPrefix(p, "login/") && !strings.HasPrefix(p, "email/") {
			t.Errorf("path %q is outside the two theme types this theme ships", p)
		}
	}
}

func TestThemePropertiesShape(t *testing.T) {
	props := string(Files(acme)[PathThemeProperties])

	for _, want := range []string{
		// Extending the bundled theme is the safety property: unoverridden
		// screens keep working. A parent change is a deliberate decision.
		"parent=keycloak.v2",
		// The parent's stylesheet must stay in the list (child-first lookup
		// falls back to the parent for it), ours appended after.
		"styles=css/styles.css css/planton.css",
		// The OS must not flip the page out of the dark design.
		"darkMode=false",
	} {
		if !strings.Contains(props, want) {
			t.Errorf("theme.properties missing %q", want)
		}
	}
}

func TestEmailThemePropertiesCarryTheInstallsFacts(t *testing.T) {
	props := string(Files(acme)[PathEmailThemeProperties])

	for _, want := range []string{
		// Inheriting Keycloak's bundled email type keeps every message it can
		// send renderable; this theme overrides the layout and a few bodies.
		"parent=keycloak",
		"brandName=Acme Platform",
		"consoleUrl=https://planton.acme.com",
		"consoleHost=planton.acme.com",
		"replyTo=it-help@acme.com",
	} {
		if !strings.Contains(props, want) {
			t.Errorf("email/theme.properties missing %q in:\n%s", want, props)
		}
	}

	bare := string(Files(EmailFacts{BrandName: "Planton"})[PathEmailThemeProperties])
	for _, want := range []string{"brandName=Planton\n", "consoleUrl=\n", "consoleHost=\n", "replyTo=\n"} {
		if !strings.Contains(bare, want) {
			t.Errorf("an install with no console and no reply-to must still write %q (empty is honest) in:\n%s", want, bare)
		}
	}

	multiline := string(Files(EmailFacts{BrandName: "Acme\nPlatform"})[PathEmailThemeProperties])
	if !strings.Contains(multiline, "brandName=Acme Platform\n") {
		t.Errorf("a newline in a fact must not start a new property: %q", multiline)
	}
}

func TestConsoleHost(t *testing.T) {
	for in, want := range map[string]string{
		"":                              "",
		"https://planton.acme.com":      "planton.acme.com",
		"https://planton.acme.com:8443": "planton.acme.com:8443",
		"http://localhost:8090/":        "localhost:8090",
	} {
		if got := (EmailFacts{ConsoleURL: in}).ConsoleHost(); got != want {
			t.Errorf("ConsoleHost(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestEmailLayoutIsGeneratedFreeMarkerReadingTheFacts(t *testing.T) {
	files := Files(acme)
	html := string(files[PathEmailHTMLLayout])
	text := string(files[PathEmailTextLayout])

	for name, layout := range map[string]string{"html": html, "text": text} {
		if !strings.Contains(layout, "Generated by @planton/email-templates") {
			t.Errorf("%s layout is not the generated artifact; run the platform's `make email-templates`", name)
		}
		if strings.Contains(layout, "{{") || strings.Contains(layout, "__FTL_") {
			t.Errorf("%s layout carries compile-time syntax: %s", name, layout)
		}
		for _, property := range []string{"properties.brandName", "properties.consoleUrl", "properties.consoleHost", "properties.replyTo"} {
			if !strings.Contains(layout, property) {
				t.Errorf("%s layout does not read %s", name, property)
			}
		}
	}
	if !strings.HasPrefix(html, `<#ftl output_format="HTML">`) {
		t.Errorf("the html layout must declare HTML output so every interpolation is escaped")
	}
	for _, macro := range []string{`emailLayout preview=""`, "heading", "paragraph", "muted", "button href", "fallbackLink href", "facts", "fact label", "code"} {
		if !strings.Contains(html, "<#macro "+macro+">") {
			t.Errorf("html layout is missing macro %q", macro)
		}
	}
	if !strings.Contains(text, "<#macro textLayout>") {
		t.Errorf("text layout is missing the textLayout macro")
	}
	// A credential-adjacent email must fetch nothing from third parties; the
	// doctype's DTD identifier is a name, not a fetch.
	withoutDoctype := regexp.MustCompile(`<!DOCTYPE[^>]*>`).ReplaceAllString(html, "")
	if strings.Contains(withoutDoctype, "http://") || strings.Contains(withoutDoctype, "https://") {
		t.Errorf("the html layout references an external URL; the frame must be self-contained")
	}
}

func TestEveryMessageTemplateComposesTheLayout(t *testing.T) {
	files := Files(acme)
	importsLayout := regexp.MustCompile(`<#import "template\.ftl" as layout>`)
	for p, content := range files {
		if !strings.HasPrefix(p, "email/html/") && !strings.HasPrefix(p, "email/text/") {
			continue
		}
		if strings.HasSuffix(p, "/template.ftl") {
			continue
		}
		body := string(content)
		if !importsLayout.MatchString(body) {
			t.Errorf("%s does not import the layout; every identity email wears the same frame", p)
		}
		want := "<@layout.emailLayout"
		if strings.HasPrefix(p, "email/text/") {
			want = "<@layout.textLayout>"
			if !strings.HasPrefix(body, `<#ftl output_format="plainText">`) {
				t.Errorf("%s must declare plainText output", p)
			}
		}
		if !strings.Contains(body, want) {
			t.Errorf("%s does not compose %s", p, want)
		}
		if !strings.Contains(body, "properties.brandName") {
			t.Errorf("%s never names the install (properties.brandName)", p)
		}
		if strings.Contains(body, "realmName") {
			t.Errorf("%s names the realm; emails name the install's brand, never the realm", p)
		}
	}
	for _, message := range []string{"password-reset", "executeActions", "email-verification", "email-test"} {
		if _, ok := files["email/html/"+message+".ftl"]; !ok {
			t.Errorf("no html body for %s", message)
		}
		if _, ok := files["email/text/"+message+".ftl"]; !ok {
			t.Errorf("no text body for %s (Keycloak renders both parts)", message)
		}
	}
}

func TestMessagesCarryTheSubjects(t *testing.T) {
	messages := string(Files(acme)[PathEmailMessages])
	for _, key := range []string{"passwordResetSubject=", "executeActionsSubject=", "emailVerificationSubject=", "emailTestSubject="} {
		if !strings.Contains(messages, key) {
			t.Errorf("messages_en.properties is missing %s", key)
		}
	}
	if strings.Contains(messages, "KEYCLOAK") {
		t.Errorf("the stock [KEYCLOAK] subject survived: %s", messages)
	}
}

func TestStylesCarryTheDesignTokens(t *testing.T) {
	css := string(Files(acme)[PathStylesCSS])

	// The load-bearing token values, byte-exact. Source of truth is the
	// console's theme package (the platform's design tokens) -- if this
	// test fails after a console token change, update the stylesheet with
	// it (that pairing is the documented contract).
	for token, value := range map[string]string{
		"page background":   "--planton-bg: #0d1117",
		"card surface":      "--planton-surface: #161b22",
		"border":            "--planton-border: #30363d",
		"primary text":      "--planton-text: #b0b8c2",
		"button background": "--planton-btn-bg: #e6edf3",
		"error":             "--planton-error: #f85149",
		"focus accent":      "--planton-focus-border: #696741",
		"font self-hosting": "url('../fonts/inter-latin.woff2')",
		"logo self-hosting": "url('../img/planton-logo.svg')",
		"no photo backdrop": "--keycloak-bg-logo-url: none",
	} {
		if !strings.Contains(css, value) {
			t.Errorf("stylesheet missing the %s token (%q)", token, value)
		}
	}

	// A credential page must fetch nothing from third parties.
	for _, forbidden := range []string{"http://", "https://"} {
		if strings.Contains(css, forbidden) {
			t.Errorf("stylesheet references an external URL (%q found) -- the theme must be fully self-contained", forbidden)
		}
	}
}

func TestFontIsRealWOFF2(t *testing.T) {
	font := Files(acme)[PathInterFontWOFF2]
	if !bytes.HasPrefix(font, []byte("wOF2")) {
		t.Fatalf("embedded font does not start with the woff2 magic bytes")
	}
}

func TestLogoIsTheConsoleMark(t *testing.T) {
	svg := string(Files(acme)[PathLogoSVG])
	if !strings.Contains(svg, `fill="#FBFBFB"`) {
		t.Errorf("logo is not the white (dark-background) mark")
	}
	if !strings.Contains(svg, `viewBox="0 0 28 32"`) {
		t.Errorf("logo geometry differs from the console asset")
	}
}

func TestHashIsDeterministicAndFollowsTheFacts(t *testing.T) {
	first := Hash(acme)
	second := Hash(acme)
	if first != second {
		t.Fatalf("Hash() is not deterministic: %q vs %q", first, second)
	}
	if len(first) != 64 {
		t.Fatalf("Hash() is not a sha256 hex string: %q", first)
	}
	renamed := acme
	renamed.BrandName = "Acme Cloud"
	if Hash(renamed) == first {
		t.Errorf("a changed brand name must change the hash: the identity pod rolls to pick up what its emails say")
	}
}

func TestTotalSizeFitsTheConfigMapBudget(t *testing.T) {
	total := 0
	for _, content := range Files(acme) {
		total += len(content)
	}
	if total > configMapSizeBudget {
		t.Fatalf("theme totals %d bytes, over the %d budget (ConfigMap ceiling is 1MiB; keep headroom)", total, configMapSizeBudget)
	}
}
